### ISSUE TITLE
Python Import pybrake

### ISSUE THREAD

**Issue by katherinegvv** [airbrake/pybrake#134]
After install pybrake, I tried import pybrake on python shell and gave error!

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/vagrant/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/pybrake/__init__.py", line 1, in <module>
    from .notifier import Notifier
  File "/home/vagrant/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)

**Comment by phumpal** [comment]
@katherinegvv this seems to be an issue w/pycharm and not necessarily pybrake. Can you check `PATH` and/or `PYTHONPATH` are configured appropriately in pycharm?

What happens if you run python from the cli? e.g

```
➜  ~ python
Python 3.8.6 (default, Oct  8 2020, 14:06:32)
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybrake
>>>
```
