### ISSUE TITLE
tdigest should be added to install_requires of setup.py

### ISSUE THREAD

**Issue by momyc** [airbrake/pybrake#70]
tdigest should be added to install_requires of setup.py.
Right now it's impossible to install pybrake from github unless tdigest is already installed.
```
Obtaining pybrake from git+https://github.com/airbrake/pybrake.git#egg=pybrake (from -r requirements.txt (line 22))
  Cloning https://github.com/airbrake/pybrake.git to ./src/pybrake
  Running setup.py (path:/var/app/src/pybrake/setup.py) egg_info for package pybrake
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/var/app/src/pybrake/setup.py", line 3, in <module>
        import pybrake
      File "/var/app/src/pybrake/pybrake/__init__.py", line 1, in <module>
        from .notifier import Notifier
      File "/var/app/src/pybrake/pybrake/notifier.py", line 14, in <module>
        from .routes import RouteStats
      File "/var/app/src/pybrake/pybrake/routes.py", line 7, in <module>
        from tdigest import TDigest
    ImportError: No module named 'tdigest'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/var/app/src/pybrake/setup.py", line 3, in <module>

    import pybrake

  File "/var/app/src/pybrake/pybrake/__init__.py", line 1, in <module>

    from .notifier import Notifier

  File "/var/app/src/pybrake/pybrake/notifier.py", line 14, in <module>

    from .routes import RouteStats

  File "/var/app/src/pybrake/pybrake/routes.py", line 7, in <module>

    from tdigest import TDigest

ImportError: No module named 'tdigest'
```

**Comment by momyc** [comment]
The problem is that pybrake is imported by setup.py just to get a version. That's not gonna work.

**Comment by momyc** [comment]
#71 fixes this issue
