### ISSUE TITLE
Facing issues in pybrake==0.4.0

### ISSUE THREAD

**Issue by vkmasters** [airbrake/pybrake#86]
@vmihailenco I have been facing issue in pybrake version 0.4.0. It works perfectly while running locally but when I deployed my django application to AWS lambda via Zappa, pybrake throws error in application.

Below is the error snippet. It seems that there is an error while importing pybrake. 
pybrake 0.3.5 works perfectly well on both scenarios. The newest version has some problem.

```
sk/handler.py", line 245, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 151, in __init__
  wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
  File "/var/task/zappa/ext/django_zappa.py", line 20, in get_django_wsgi
  return get_wsgi_application()
  File "/var/task/django/core/wsgi.py", line 12, in get_wsgi_application
  django.setup(set_prefix=False)
  File "/var/task/django/__init__.py", line 19, in setup
  configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/var/task/django/conf/__init__.py", line 56, in __getattr__
  self._setup(name)
  File "/var/task/django/conf/__init__.py", line 43, in _setup
  self._wrapped = Settings(settings_module)
  File "/var/task/django/conf/__init__.py", line 106, in __init__
  mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/pos_authoriser/settings.py", line 15, in <module>
  import pybrake
  File "/var/task/pybrake/__init__.py", line 1, in <module>
  from .notifier import Notifier
  File "/var/task/pybrake/notifier.py", line 14, in <module>
  from .routes import RouteStats
  File "/var/task/pybrake/routes.py", line 7, in <module>
  from .tdigest import as_bytes, TDigestStat
  File "/var/task/pybrake/tdigest.py", line 4, in <module>
  import tdigest
  File "/var/task/tdigest/__init__.py", line 1, in <module>
  from .tdigest import TDigest
  File "/var/task/tdigest/tdigest.py", line 5, in <module>
  from accumulation_tree import AccumulationTree
  File "/var/task/accumulation_tree/__init__.py", line 2, in <module>
  from .accumulation_tree import AccumulationTree
ImportError: /var/task/accumulation_tree/accumulation_tree.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
[1562696051691] [DEBUG] 2019-07-09T18:14:11.691Z 9cb5828e-6072-4ae4-a0c3-2be817ac9c13 Zappa Event: {'resource': '/', 'path': '/', 'httpMethod': 'GET', 'headers': {'Accept':
'*/*', 'accept-encoding': 'gzip, deflate', 'Authorization': 'Token token=abxckjhd btoken=oiyasdfjkhgk', 'Cache-Control': 'no-cache', 'Host': '2cv1y57cua.execute-api.us-east-1.amazonaws.com', 'Postman-Token': 'b0d1b3b3-0c01-420d-ac4f-f0f829c0d44e', 'User-Agent': 'PostmanRuntime/7.15.0', 'X-Amzn-Trace-Id': 'Root=1-5d24d973-59bcdf2478839d3a4b9ed36a', 'X-Forwarded-For': '150.107.189.220', 'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https'}, 'multiValueHeaders': {'Accept': ['*/*'], 'accept-encoding': ['gzip, deflate'], 'Authorization': ['Token token=abxckjhd btoken=oiyasdfjkhgk'], 'Cache-Control': ['no-cache'], 'Host': ['2cv1y57cua.execute-api.us-east-1.amazonaws.com'], 'Postman-Token': ['b0d1b3b3-0c01-420d-ac4f-f0f829c0d44e'], 'User-Agent': ['PostmanRuntime/7.15.0'], 'X-Amzn-Trace-Id': ['Root=1-5d24d973-59bcdf2478839d3a4b9ed36a'], 'X-Forwarded-For': ['150.107.189.220'], 'X-Forwarded-Port': ['443'], 'X-Forwarded-Proto': ['https']}, 'queryStringParameters': None, 'multiValueQueryStringParameters': None, 'pathParameters': None, 'stageVariables': None, 'requestContext': {'resourceId': 'o3li2ozlsb', 'resourcePath': '/', 'httpMethod': 'GET', 'extendedRequestId': 'ckbqEEFYIAMF2qQ=', 'requestTime':
'09/Jul/2019:18:14:11 +0000', 'path': '/dev/', 'accountId': '232720106935', 'protocol': 'HTTP/1.1', 'stage': 'dev', 'domainPrefix': '2cv1y57cua', 'requestTimeEpoch': 1562696051622, 'requestId': '59fe1dce-a275-11e9-877b-6778d891367b', 'identity': {'cognitoIdentityPoolId': None, 'accountId': None, 'cognitoIdentityId': None, 'caller': None, 'sourceIp': '150.107.189.220', 'principalOrgId': None, 'accessKey': None, 'cognitoAuthenticationType': None, 'cognitoAuthenticationProvider': None, 'userArn': None, 'userAgent': 'PostmanRuntime/7.15.0', 'user': None}, 'domainName': '2cv1y57cua.execute-api.us-east-1.amazonaws.com', 'apiId': '2cv1y57cua'}, 'body': None, 'isBase64Encoded': False}
[1562696051691] [DEBUG] 2019-07-09T18:14:11.691Z 9cb5828e-6072-4ae4-a0c3-2be817ac9c13 host found: [2cv1y57cua.execute-api.us-east-1.amazonaws.com]
[1562696051691] [DEBUG] 2019-07-09T18:14:11.691Z 9cb5828e-6072-4ae4-a0c3-2be817ac9c13 amazonaws found in host
[1562696051698] 'NoneType' object is not callable
[1562696103648] Instancing..
[1562696106711] /var/task/accumulation_tree/accumulation_tree.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 602, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 245, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 151, in __init__
  wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
  File "/var/task/zappa/ext/django_zappa.py", line 20, in get_django_wsgi
  return get_wsgi_application()
  File "/var/task/django/core/wsgi.py", line 12, in get_wsgi_application
  django.setup(set_prefix=False)
  File "/var/task/django/__init__.py", line 19, in setup
  configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/var/task/django/conf/__init__.py", line 56, in __getattr__
  self._setup(name)
  File "/var/task/django/conf/__init__.py", line 43, in _setup
  self._wrapped = Settings(settings_module)
  File "/var/task/django/conf/__init__.py", line 106, in __init__
  mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/pos_authoriser/settings.py", line 15, in <module>
  import pybrake
  File "/var/task/pybrake/__init__.py", line 1, in <module>
  from .notifier import Notifier
  File "/var/task/pybrake/notifier.py", line 14, in <module>
  from .routes import RouteStats
  File "/var/task/pybrake/routes.py", line 7, in <module>
  from .tdigest import as_bytes, TDigestStat
  File "/var/task/pybrake/tdigest.py", line 4, in <module>
  import tdigest
  File "/var/task/tdigest/__init__.py", line 1, in <module>
  from .tdigest import TDigest
  File "/var/task/tdigest/tdigest.py", line 5, in <module>
  from accumulation_tree import AccumulationTree
  File "/var/task/accumulation_tree/__init__.py", line 2, in <module>
  from .accumulation_tree import AccumulationTree
ImportError: /var/task/accumulation_tree/accumulation_tree.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
```

**Comment by vmihailenco** [comment]
It looks like AWS lambda does not support Cython which is used by accumulation_tree module. I guess the fix would be to disable tdigest and APM on such platforms...
